name: facepunch
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# F:\flutter_sdks\sdk\flutter_2.5.3\bin\flutter.bat --no-color build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --no-tree-shake-icons
version: 2.0.0+41

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_ml_kit: ^0.7.3
  camera: ^0.9.4+16
  provider: ^6.0.1
  localstorage: ^4.0.0+1
  shared_preferences: ^2.0.8
  rounded_loading_button: ^2.0.9
  permission_handler: ^8.3.0
  sliding_up_panel: ^2.0.0+1
  firebase_messaging: ^11.1.0
  pin_code_text_field: ^1.8.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0+1
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.4+4
  geolocator: ^7.7.1
  intl: ^0.17.0
  flutter_date_pickers: ^0.2.6
  google_maps_flutter: ^2.1.1
  flutter_slidable: ^1.1.0
  syncfusion_flutter_pdfviewer: ^19.3.54-beta
  flutter_colorpicker: ^1.0.2
  flutter_localizations:
    sdk: flutter
  wakelock: ^0.5.6
  url_launcher: ^6.0.13
  path_provider: ^2.0.7
  path: ^1.8.0
  nfc_manager: ^3.1.0
  image_cropper: ^1.4.1
  device_info: ^2.0.3
  assets_audio_player: ^3.0.4+1
  loader_overlay: ^2.0.5
  dropdown_search: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/country.json
    - assets/sound/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
